project:
  type: website

website:
  title: "Visual Analytics"
  navbar:
    left:
      - href: KunruiWang-Takehome1.qmd
        text: Exercise 1    
      - href: KunruiWang-Takehome2.qmd
        text: Exercise 2
      - href: KunruiWang-Takehome3.qmd
        text: Exercise 3
      - href: KunruiWang-Takehome4.qmd
        text: Exercise 4
      - href: KunruiWang-Handson.qmd
        text: Hands-on Exercise
      - href: index.qmd
        text: Return Home
        
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

