project:
  type: website

website:
  title: "VisualAnalytics"
  navbar:
    left:
      - href: KunruiWang-Takehome2.qmd
        text: Take Home Exercise 2
      - href: KunruiWang-Takehome3.qmd
        text: Take Home Exercise 3
      - href: KunruiWang-Takehome4.qmd
        text: Take Home Exercise 4
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

